name: Issue Comments Validate
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  issue_comment:
    name: Issue Comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@v2
      - name: Validate
        id: validate
        uses: fukuiretu/actions-issue-comment-validates@main
        with:
          debug: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report
        id: report
        env:
          HTML_URL: ${{ github.event.comment.html_url }}
          ID: ${{ github.event.comment.id }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "Issue $NUMBER has had a comment (ID: $ID) with restricted words: ${{ steps.validate.outputs.check1 }}. Moderate at $HTML_URL if true"